Repository konstellation-io/kai-sdk, pull requests merged in 2023-10, with the labels that each got.

#47 Feature/app config field validations
  demo/training-workflow/src/github-trigger-mock/main.py
  go-sdk/go.mod
  go-sdk/go.sum
  go-sdk/runner/exit/exit_runner.go
  go-sdk/runner/exit/subscriber.go
  go-sdk/runner/runner.go
  go-sdk/runner/runner_test.go
  go-sdk/runner/task/subscriber.go
  go-sdk/runner/task/task_runner.go
  go-sdk/runner/trigger/helpers.go
  go-sdk/runner/trigger/trigger_runner.go
  py-sdk/runner/runner/exit/exit_runner.py
  py-sdk/runner/runner/exit/subscriber.py
  py-sdk/runner/runner/runner.py
  py-sdk/runner/runner/runner_test.py
  py-sdk/runner/runner/task/subscriber.py
  py-sdk/runner/runner/task/task_runner.py
  py-sdk/runner/runner/trigger/subscriber.py
  py-sdk/runner/runner/trigger/trigger_runner.py
  testdata/config.yaml
Labels: size/m

#51 Feature/new scope centralized configuration
  demo/cronjob-trigger-py/app.yaml
  demo/cronjob-trigger-py/main.py
  demo/exit-py/app.yaml
  demo/nats-trigger-py/app.yaml
  demo/task-py/app.yaml
  py-sdk/runner/runner/common/common_test.py
  py-sdk/runner/runner/exit/exit_runner.py
  py-sdk/runner/runner/runner.py
  py-sdk/runner/runner/runner_test.py
  py-sdk/runner/runner/task/task_runner.py
  py-sdk/sdk/sdk/centralized_config/centralized_config.py
  py-sdk/sdk/sdk/centralized_config/centralized_config_test.py
  py-sdk/sdk/sdk/kai_sdk_test.py
Labels: size/m

#53 Feature/add global scope go sdk
  Makefile
  demo/cronjob-trigger/app.yaml
  demo/exit/app.yaml
  demo/nats-trigger/app.yaml
  demo/rest-trigger/app.yaml
  demo/task/app.yaml
  go-sdk/runner/runner.go
  go-sdk/sdk/centralized-configuration/centralized_configuration.go
  go-sdk/sdk/centralized-configuration/centralized_configuration_delete_test.go
  go-sdk/sdk/centralized-configuration/centralized_configuration_get_test.go
  go-sdk/sdk/centralized-configuration/centralized_configuration_set_test.go
  go-sdk/sdk/centralized-configuration/centralized_configuration_test.go
  go-sdk/sdk/centralized-configuration/export_test.go
  go-sdk/sdk/messaging/messaging.go
  go-sdk/sdk/metadata/metadata.go
  go-sdk/sdk/metadata/metadata_test.go
  py-sdk/sdk/sdk/metadata/metadata.py
  py-sdk/sdk/sdk/metadata/metadata_test.py
  testdata/config.yaml
Labels: size/m

#60 feature(demo): Add init.py
  demo/cronjob-trigger-py/__init__.py
  demo/exit-py/__init__.py
  demo/nats-trigger-py/__init__.py
  demo/task-py/__init__.py
Labels: size/xs

#59 Feature/improve logs
  demo/cronjob-trigger-py/main.py
  demo/cronjob-trigger/main.go
  demo/exit-py/main.py
  demo/exit/main.go
  demo/nats-trigger-py/main.py
  demo/nats-trigger/main.go
  demo/rest-trigger/main.go
  demo/task-py/main.py
  demo/task/main.go
  go-sdk/mocks/jetstream_context_mock.go
  go-sdk/mocks/key_value_entry_mock.go
  go-sdk/mocks/key_value_mock.go
  go-sdk/mocks/messaging_mock.go
  go-sdk/mocks/messaging_utils_mock.go
  go-sdk/mocks/metadata_mock.go
  go-sdk/mocks/nats_object_store_mock.go
  go-sdk/mocks/path_utils_mock.go
  go-sdk/protos/kai_nats_msg.pb.go
  go-sdk/sdk/kai_sdk.go
  go-sdk/sdk/metadata/metadata.go
  go-sdk/sdk/metadata/metadata_test.go
  py-sdk/runner/runner/exit/helpers.py
  py-sdk/runner/runner/exit/subscriber.py
  py-sdk/runner/runner/runner.py
  py-sdk/runner/runner/runner_test.py
  py-sdk/runner/runner/task/helpers.py
  py-sdk/runner/runner/task/subscriber.py
  py-sdk/runner/runner/trigger/helpers.py
  py-sdk/runner/runner/trigger/subscriber.py
  py-sdk/sdk/sdk/kai_sdk.py
  py-sdk/sdk/sdk/messaging/messaging.py
  py-sdk/sdk/sdk/metadata/metadata.py
  py-sdk/sdk/sdk/metadata/metadata_test.py
Labels: size/l

#57 Add request id to logging
  demo/cronjob-trigger/go.mod
  demo/cronjob-trigger/go.sum
  demo/cronjob-trigger/main.go
  demo/exit/go.mod
  demo/exit/go.sum
  demo/nats-trigger/go.mod
  demo/nats-trigger/go.sum
  demo/nats-trigger/main.go
  demo/rest-trigger/go.mod
  demo/rest-trigger/go.sum
  demo/task/go.mod
  demo/task/go.sum
  go-sdk/go.mod
  go-sdk/go.sum
  go-sdk/internal/common/kai_constants.go
  go-sdk/mocks/centralized_config_mock.go
  go-sdk/mocks/jetstream_context_mock.go
  go-sdk/mocks/key_value_entry_mock.go
  go-sdk/mocks/key_value_mock.go
  go-sdk/mocks/measurements_mock.go
  go-sdk/mocks/messaging_mock.go
  go-sdk/mocks/messaging_utils_mock.go
  go-sdk/mocks/metadata_mock.go
  go-sdk/mocks/nats_object_store_mock.go
  go-sdk/mocks/path_utils_mock.go
  go-sdk/runner/exit/helpers.go
  go-sdk/runner/exit/subscriber.go
  go-sdk/runner/runner.go
  go-sdk/runner/task/helpers.go
  go-sdk/runner/task/subscriber.go
  go-sdk/runner/trigger/helpers.go
  go-sdk/runner/trigger/subscriber.go
  go-sdk/sdk/centralized-configuration/centralized_configuration_test.go
  go-sdk/sdk/ephemeral-storage/ephemeral_storage_test.go
  go-sdk/sdk/kai_sdk.go
  go-sdk/sdk/messaging/messaging_internals.go
Labels: size/xl

#67 feat: update sdk version v0.3.0
  py-sdk/sdk/poetry.lock
  py-sdk/sdk/pyproject.toml
Labels: size/s

#68 feature: update runner v0.4.0
  py-sdk/runner/poetry.lock
  py-sdk/runner/pyproject.toml
Labels: size/s

#70 feat(go-sdk): new method get request id given nats message
  go-sdk/mocks/jetstream_context_mock.go
  go-sdk/mocks/key_value_entry_mock.go
  go-sdk/mocks/key_value_mock.go
  go-sdk/mocks/messaging_mock.go
  go-sdk/mocks/messaging_utils_mock.go
  go-sdk/mocks/metadata_mock.go
  go-sdk/mocks/nats_object_store_mock.go
  go-sdk/mocks/path_utils_mock.go
  go-sdk/sdk/kai_sdk.go
  go-sdk/sdk/messaging/messaging_internals.go
  go-sdk/sdk/messaging/messaging_test.go
  py-sdk/sdk/sdk/messaging/exceptions.py
  py-sdk/sdk/sdk/messaging/messaging.py
  py-sdk/sdk/sdk/messaging/messaging_test.py
Labels: size/m

#75 release 1.2.1
  demo/cronjob-trigger-py/poetry.lock
  demo/cronjob-trigger/go.mod
  demo/cronjob-trigger/go.sum
  demo/exit-py/poetry.lock
  demo/exit/go.mod
  demo/exit/go.sum
  demo/nats-trigger-py/poetry.lock
  demo/nats-trigger/go.mod
  demo/nats-trigger/go.sum
  demo/rest-trigger/go.mod
  demo/rest-trigger/go.sum
  demo/task-py/poetry.lock
  demo/task/go.mod
  demo/task/go.sum
  go-sdk/mocks/jetstream_context_mock.go
  go-sdk/mocks/key_value_entry_mock.go
  go-sdk/mocks/key_value_mock.go
  go-sdk/mocks/messaging_mock.go
  go-sdk/mocks/messaging_utils_mock.go
  go-sdk/mocks/metadata_mock.go
  go-sdk/mocks/nats_object_store_mock.go
  go-sdk/mocks/path_utils_mock.go
  go-sdk/runner/exit/subscriber.go
  go-sdk/runner/runner.go
  go-sdk/runner/task/subscriber.go
  go-sdk/runner/trigger/subscriber.go
  go-sdk/sdk/kai_sdk.go
  go-sdk/sdk/messaging/messaging_internals.go
  go-sdk/sdk/messaging/messaging_send_any_test.go
  go-sdk/sdk/messaging/messaging_test.go
  go-sdk/sdk/metadata/metadata.go
  go-sdk/sdk/metadata/metadata_test.go
  py-sdk/poetry.lock
  py-sdk/runner/poetry.lock
  py-sdk/runner/pyproject.toml
  py-sdk/runner/runner/runner.py
  py-sdk/sdk/poetry.lock
  py-sdk/sdk/pyproject.toml
  py-sdk/sdk/sdk/messaging/exceptions.py
  py-sdk/sdk/sdk/messaging/messaging.py
  py-sdk/sdk/sdk/messaging/messaging_test.py
  py-sdk/sdk/sdk/metadata/metadata.py
  py-sdk/sdk/sdk/metadata/metadata_test.py
  testdata/config.yaml
Labels: size/l

#73 feat: add persistant storage methods to Python SDK
  demo/cronjob-trigger-py/app.yaml
  demo/cronjob-trigger/app.yaml
  demo/exit-py/app.yaml
  demo/exit-py/main.py
  demo/exit/app.yaml
  demo/nats-trigger-py/app.yaml
  demo/nats-trigger/app.yaml
  demo/rest-trigger/app.yaml
  demo/task-py/app.yaml
  demo/task/app.yaml
  go-sdk/runner/runner.go
  py-sdk/README.md
  py-sdk/poetry.lock
  py-sdk/pyproject.toml
  py-sdk/runner/runner/common/common_test.py
  py-sdk/runner/runner/exit/exit_runner.py
  py-sdk/runner/runner/exit/exit_runner_test.py
  py-sdk/runner/runner/exit/helpers_test.py
  py-sdk/runner/runner/exit/subscriber_test.py
  py-sdk/runner/runner/runner.py
  py-sdk/runner/runner/runner_test.py
  py-sdk/runner/runner/task/helpers_test.py
  py-sdk/runner/runner/task/subscriber_test.py
  py-sdk/runner/runner/task/task_runner.py
  py-sdk/runner/runner/task/task_runner_test.py
  py-sdk/runner/runner/trigger/helpers_test.py
  py-sdk/runner/runner/trigger/subscriber.py
  py-sdk/runner/runner/trigger/subscriber_test.py
  py-sdk/runner/runner/trigger/trigger_runner.py
  py-sdk/runner/runner/trigger/trigger_runner_test.py
  py-sdk/sdk/poetry.lock
  py-sdk/sdk/pyproject.toml
  py-sdk/sdk/sdk/centralized_config/centralized_config.py
  py-sdk/sdk/sdk/centralized_config/centralized_config_test.py
  py-sdk/sdk/sdk/centralized_config/exceptions.py
  py-sdk/sdk/sdk/ephemeral_storage/ephemeral_storage.py
  py-sdk/sdk/sdk/ephemeral_storage/ephemeral_storage_test.py
  py-sdk/sdk/sdk/ephemeral_storage/exceptions.py
  py-sdk/sdk/sdk/kai_sdk_test.py
  py-sdk/sdk/sdk/messaging/exceptions.py
  py-sdk/sdk/sdk/messaging/messaging.py
  py-sdk/sdk/sdk/messaging/messaging_test.py
  py-sdk/sdk/sdk/messaging/messaging_utils.py
  py-sdk/sdk/sdk/messaging/messaging_utils_test.py
  py-sdk/sdk/sdk/persistent_storage/exceptions.py
  py-sdk/sdk/sdk/persistent_storage/persistent_storage.py
  py-sdk/sdk/sdk/persistent_storage/persistent_storage_test.py
  testdata/config.yaml
Labels: size/l

#82 feat: add krtignore file to avoid .venv being zipped
  demo/cronjob-trigger-py/.krtignore
  demo/exit-py/.krtignore
  demo/nats-trigger-py/.krtignore
  demo/task-py/.krtignore
Labels: size/xs
