Repository konstellation-io/kai-sdk, pull requests merged in 2023-12, with the labels that each got.

#125 Fix/wrong index key
  demo/cronjob-trigger-py/app.yaml
  demo/cronjob-trigger-py/pyproject.toml
  demo/cronjob-trigger/app.yaml
  demo/exit-py/app.yaml
  demo/exit-py/pyproject.toml
  demo/exit/app.yaml
  demo/metrics-py/app.yaml
  demo/metrics-py/pyproject.toml
  demo/metrics/app.yaml
  demo/nats-trigger-py/app.yaml
  demo/nats-trigger-py/pyproject.toml
  demo/nats-trigger/app.yaml
  demo/redis-py/app.yaml
  demo/redis-py/pyproject.toml
  demo/rest-trigger/app.yaml
  demo/task-py/app.yaml
  demo/task-py/pyproject.toml
  demo/task/app.yaml
  py-sdk/runner/runner/runner.py
  py-sdk/sdk/sdk/model_registry/model_registry.py
  py-sdk/sdk/sdk/predictions/store.py
  py-sdk/sdk/sdk/predictions/store_test.py
Labels: size/s

#130 Release: fix release
  demo/cronjob-trigger-py/app.yaml
  demo/cronjob-trigger-py/poetry.lock
  demo/cronjob-trigger-py/pyproject.toml
  demo/cronjob-trigger/app.yaml
  demo/exit-py/app.yaml
  demo/exit-py/poetry.lock
  demo/exit-py/pyproject.toml
  demo/exit/app.yaml
  demo/metrics-py/app.yaml
  demo/metrics-py/poetry.lock
  demo/metrics-py/pyproject.toml
  demo/metrics/app.yaml
  demo/nats-trigger-py/app.yaml
  demo/nats-trigger-py/poetry.lock
  demo/nats-trigger-py/pyproject.toml
  demo/nats-trigger/app.yaml
  demo/redis-py/app.yaml
  demo/redis-py/poetry.lock
  demo/redis-py/pyproject.toml
  demo/rest-trigger/app.yaml
  demo/task-py/app.yaml
  demo/task-py/poetry.lock
  demo/task-py/pyproject.toml
  demo/task/app.yaml
  go-sdk/sdk/measurement/measurement.go
Labels: size/l

#131 Rebase develop with main
  demo/metrics-py/otel-collector-config.yaml
  demo/metrics/otel-collector-config.yaml
Labels: size/xs

#132 feat: update dependencies
  demo/cronjob-trigger-py/poetry.lock
  demo/cronjob-trigger-py/pyproject.toml
  demo/exit-py/poetry.lock
  demo/exit-py/pyproject.toml
  demo/metrics-py/poetry.lock
  demo/metrics-py/pyproject.toml
  demo/nats-trigger-py/poetry.lock
  demo/nats-trigger-py/pyproject.toml
  demo/redis-py/poetry.lock
  demo/redis-py/pyproject.toml
  demo/task-py/poetry.lock
  demo/task-py/pyproject.toml
  py-sdk/poetry.lock
  py-sdk/pyproject.toml
  py-sdk/runner/poetry.lock
  py-sdk/runner/pyproject.toml
Labels: size/s

#133 Update py runner
  demo/cronjob-trigger-py/poetry.lock
  demo/cronjob-trigger-py/pyproject.toml
  demo/exit-py/poetry.lock
  demo/exit-py/pyproject.toml
  demo/metrics-py/poetry.lock
  demo/metrics-py/pyproject.toml
  demo/nats-trigger-py/poetry.lock
  demo/nats-trigger-py/pyproject.toml
  demo/redis-py/poetry.lock
  demo/redis-py/pyproject.toml
  demo/task-py/poetry.lock
  demo/task-py/pyproject.toml
  py-sdk/poetry.lock
  py-sdk/pyproject.toml
  py-sdk/runner/poetry.lock
  py-sdk/runner/pyproject.toml
Labels: size/s

#136 feat(sdk-go): functional and technical metrics
  go-sdk/go.mod
  go-sdk/go.sum
  go-sdk/runner/exit/exit_runner.go
  go-sdk/runner/exit/subscriber.go
  go-sdk/runner/task/subscriber.go
  go-sdk/runner/task/task_runner.go
  go-sdk/runner/trigger/subscriber.go
  go-sdk/runner/trigger/trigger_runner.go
Labels: size/m

#139 Feature/add technical metrics python sdk
  demo/redis-py/main.py
  go-sdk/runner/exit/subscriber.go
  go-sdk/runner/task/subscriber.go
  go-sdk/runner/trigger/subscriber.go
  py-sdk/runner/runner/exit/exceptions.py
  py-sdk/runner/runner/exit/exit_runner.py
  py-sdk/runner/runner/exit/exit_runner_test.py
  py-sdk/runner/runner/exit/subscriber.py
  py-sdk/runner/runner/exit/subscriber_test.py
  py-sdk/runner/runner/task/exceptions.py
  py-sdk/runner/runner/task/subscriber.py
  py-sdk/runner/runner/task/subscriber_test.py
  py-sdk/runner/runner/task/task_runner.py
  py-sdk/runner/runner/task/task_runner_test.py
  py-sdk/runner/runner/trigger/exceptions.py
  py-sdk/runner/runner/trigger/subscriber.py
  py-sdk/runner/runner/trigger/subscriber_test.py
  py-sdk/runner/runner/trigger/trigger_runner.py
  py-sdk/runner/runner/trigger/trigger_runner_test.py
  py-sdk/sdk/sdk/measurements/measurements.py
Labels: size/m

#140 Release/v1.3.3
  .github/workflows/test.yaml
  .github/workflows/utils-pr-age.yaml
  demo/redis-py/main.py
  go-sdk/go.mod
  go-sdk/go.sum
  go-sdk/runner/exit/exit_runner.go
  go-sdk/runner/exit/subscriber.go
  go-sdk/runner/task/subscriber.go
  go-sdk/runner/task/task_runner.go
  go-sdk/runner/trigger/subscriber.go
  go-sdk/runner/trigger/trigger_runner.go
  py-sdk/runner/runner/exit/exceptions.py
  py-sdk/runner/runner/exit/exit_runner.py
  py-sdk/runner/runner/exit/exit_runner_test.py
  py-sdk/runner/runner/exit/subscriber.py
  py-sdk/runner/runner/exit/subscriber_test.py
  py-sdk/runner/runner/task/exceptions.py
  py-sdk/runner/runner/task/subscriber.py
  py-sdk/runner/runner/task/subscriber_test.py
  py-sdk/runner/runner/task/task_runner.py
  py-sdk/runner/runner/task/task_runner_test.py
  py-sdk/runner/runner/trigger/exceptions.py
  py-sdk/runner/runner/trigger/subscriber.py
  py-sdk/runner/runner/trigger/subscriber_test.py
  py-sdk/runner/runner/trigger/trigger_runner.py
  py-sdk/runner/runner/trigger/trigger_runner_test.py
  py-sdk/sdk/sdk/measurements/measurements.py
Labels: size/m

#142 feat: add makefile and scripts to update dependencies, bump dependencies
  Makefile
  demo/cronjob-trigger-py/poetry.lock
  demo/cronjob-trigger-py/pyproject.toml
  demo/cronjob-trigger/go.mod
  demo/cronjob-trigger/go.sum
  demo/exit-py/poetry.lock
  demo/exit-py/pyproject.toml
  demo/exit/go.mod
  demo/exit/go.sum
  demo/metrics-py/poetry.lock
  demo/metrics-py/pyproject.toml
  demo/metrics/go.mod
  demo/metrics/go.sum
  demo/nats-trigger-py/poetry.lock
  demo/nats-trigger-py/pyproject.toml
  demo/nats-trigger/go.mod
  demo/nats-trigger/go.sum
  demo/redis-py/poetry.lock
  demo/redis-py/pyproject.toml
  demo/rest-trigger/go.mod
  demo/rest-trigger/go.sum
  demo/task-py/poetry.lock
  demo/task-py/pyproject.toml
  demo/task/go.mod
  demo/task/go.sum
  py-sdk/poetry.lock
  py-sdk/pyproject.toml
  py-sdk/runner/poetry.lock
  py-sdk/runner/pyproject.toml
  py-sdk/sdk/poetry.lock
  scripts/update_go_mod.sh
  scripts/update_poetries.sh
Labels: size/m

#144 fix: wrong default value and missing value in python
  demo/cronjob-trigger-py/app.yaml
  demo/cronjob-trigger/app.yaml
  demo/exit-py/app.yaml
  demo/exit/app.yaml
  go-sdk/runner/runner.go
  py-sdk/runner/runner/runner.py
Labels: size/s

#145 Release/v1.3.4
  Makefile
  demo/cronjob-trigger-py/app.yaml
  demo/cronjob-trigger-py/poetry.lock
  demo/cronjob-trigger-py/pyproject.toml
  demo/cronjob-trigger/app.yaml
  demo/cronjob-trigger/go.mod
  demo/cronjob-trigger/go.sum
  demo/exit-py/app.yaml
  demo/exit-py/poetry.lock
  demo/exit-py/pyproject.toml
  demo/exit/app.yaml
  demo/exit/go.mod
  demo/exit/go.sum
  demo/metrics-py/poetry.lock
  demo/metrics-py/pyproject.toml
  demo/metrics/go.mod
  demo/metrics/go.sum
  demo/nats-trigger-py/poetry.lock
  demo/nats-trigger-py/pyproject.toml
  demo/nats-trigger/go.mod
  demo/nats-trigger/go.sum
  demo/redis-py/poetry.lock
  demo/redis-py/pyproject.toml
  demo/rest-trigger/go.mod
  demo/rest-trigger/go.sum
  demo/task-py/poetry.lock
  demo/task-py/pyproject.toml
  demo/task/go.mod
  demo/task/go.sum
  go-sdk/runner/runner.go
  py-sdk/poetry.lock
  py-sdk/pyproject.toml
  py-sdk/runner/poetry.lock
  py-sdk/runner/pyproject.toml
  py-sdk/runner/runner/runner.py
  py-sdk/sdk/poetry.lock
  scripts/update_go_mod.sh
  scripts/update_poetries.sh
Labels: size/m

#150 Fix some minor issues
  go-sdk/runner/exit/exit_runner.go
  go-sdk/runner/task/task_runner.go
  py-sdk/runner/runner/exit/exit_runner.py
  py-sdk/runner/runner/runner_test.py
  py-sdk/runner/runner/task/task_runner.py
  py-sdk/sdk/sdk/model_registry/model_registry.py
  py-sdk/sdk/sdk/persistent_storage/persistent_storage.py
Labels: size/s

#151 Release/v1.3.5
  go-sdk/runner/exit/exit_runner.go
  go-sdk/runner/task/task_runner.go
  py-sdk/runner/runner/exit/exit_runner.py
  py-sdk/runner/runner/runner_test.py
  py-sdk/runner/runner/task/task_runner.py
  py-sdk/sdk/sdk/model_registry/model_registry.py
  py-sdk/sdk/sdk/persistent_storage/persistent_storage.py
Labels: size/s

#153 Feature/bump sdk
  demo/cronjob-trigger-py/pyproject.toml
  demo/exit-py/pyproject.toml
  demo/metrics-py/pyproject.toml
  demo/nats-trigger-py/pyproject.toml
  demo/redis-py/pyproject.toml
  demo/task-py/pyproject.toml
  py-sdk/pyproject.toml
  py-sdk/runner/poetry.lock
  py-sdk/runner/pyproject.toml
Labels: size/s

#154 Release/v1.3.6
  demo/cronjob-trigger-py/pyproject.toml
  demo/exit-py/pyproject.toml
  demo/metrics-py/pyproject.toml
  demo/nats-trigger-py/pyproject.toml
  demo/redis-py/pyproject.toml
  demo/task-py/pyproject.toml
  py-sdk/pyproject.toml
  py-sdk/runner/poetry.lock
  py-sdk/runner/pyproject.toml
Labels: size/s

#156 fix: missing metrics, wrong default folder name
  py-sdk/runner/runner/exit/subscriber.py
  py-sdk/runner/runner/runner.py
  py-sdk/runner/runner/task/subscriber.py
  py-sdk/runner/runner/trigger/subscriber.py
Labels: size/s

#158 Release/v1.3.7
  py-sdk/runner/runner/exit/subscriber.py
  py-sdk/runner/runner/runner.py
  py-sdk/runner/runner/task/subscriber.py
  py-sdk/runner/runner/trigger/subscriber.py
Labels: size/s

#159 Fix/get version registry missing logic
  go-sdk/sdk/model-registry/model_registry.go
  py-sdk/sdk/sdk/model_registry/exceptions.py
  py-sdk/sdk/sdk/model_registry/model_registry.py
  py-sdk/sdk/sdk/model_registry/model_registry_test.py
  py-sdk/sdk/sdk/persistent_storage/persistent_storage.py
Labels: size/m

#161 Release/v1.3.8
  go-sdk/sdk/model-registry/model_registry.go
  py-sdk/sdk/sdk/model_registry/exceptions.py
  py-sdk/sdk/sdk/model_registry/model_registry.py
  py-sdk/sdk/sdk/model_registry/model_registry_test.py
  py-sdk/sdk/sdk/persistent_storage/persistent_storage.py
Labels: size/m

#163 chore: bump dependencies
  demo/cronjob-trigger-py/pyproject.toml
  demo/exit-py/pyproject.toml
  demo/metrics-py/pyproject.toml
  demo/nats-trigger-py/pyproject.toml
  demo/redis-py/pyproject.toml
  demo/task-py/pyproject.toml
  py-sdk/pyproject.toml
  py-sdk/runner/poetry.lock
  py-sdk/runner/pyproject.toml
Labels: size/s

#164 Release/v1.3.9
  demo/cronjob-trigger-py/pyproject.toml
  demo/exit-py/pyproject.toml
  demo/metrics-py/pyproject.toml
  demo/nats-trigger-py/pyproject.toml
  demo/redis-py/pyproject.toml
  demo/task-py/pyproject.toml
  py-sdk/pyproject.toml
  py-sdk/runner/poetry.lock
  py-sdk/runner/pyproject.toml
Labels: size/s

#168 fix: fix method and update tests
  py-sdk/sdk/sdk/model_registry/model_registry.py
  py-sdk/sdk/sdk/model_registry/model_registry_test.py
Labels: size/s

#169 Release/v1.3.10
  py-sdk/sdk/sdk/model_registry/model_registry.py
  py-sdk/sdk/sdk/model_registry/model_registry_test.py
Labels: size/s

#171 chore: bump version
  py-sdk/runner/poetry.lock
  py-sdk/runner/pyproject.toml
Labels: size/xs

#172 Release/v1.3.11
  py-sdk/runner/poetry.lock
  py-sdk/runner/pyproject.toml
Labels: size/xs

#174 fix: wrong name
  py-sdk/sdk/sdk/model_registry/model_registry.py
Labels: size/s

#175 Release/v1.3.12
  py-sdk/sdk/sdk/model_registry/model_registry.py
Labels: size/s

#177 chore: bump sdk
  py-sdk/runner/poetry.lock
  py-sdk/runner/pyproject.toml
Labels: size/m

#178 Release/v1.3.13
  py-sdk/runner/poetry.lock
  py-sdk/runner/pyproject.toml
Labels: size/m

#143 Fix/duplicated python error logs
  demo/cronjob-trigger-py/poetry.lock
  demo/cronjob-trigger-py/pyproject.toml
  demo/cronjob-trigger/go.mod
  demo/cronjob-trigger/go.sum
  demo/exit-py/poetry.lock
  demo/exit-py/pyproject.toml
  demo/exit/go.mod
  demo/exit/go.sum
  demo/metrics-py/poetry.lock
  demo/metrics-py/pyproject.toml
  demo/metrics/go.mod
  demo/metrics/go.sum
  demo/nats-trigger-py/poetry.lock
  demo/nats-trigger-py/pyproject.toml
  demo/nats-trigger/go.mod
  demo/nats-trigger/go.sum
  demo/redis-py/poetry.lock
  demo/redis-py/pyproject.toml
  demo/rest-trigger/go.mod
  demo/rest-trigger/go.sum
  demo/task-py/poetry.lock
  demo/task-py/pyproject.toml
  demo/task/go.mod
  demo/task/go.sum
  py-sdk/poetry.lock
  py-sdk/pyproject.toml
  py-sdk/runner/runner/exit/exit_runner.py
  py-sdk/runner/runner/runner.py
  py-sdk/runner/runner/task/task_runner.py
  py-sdk/runner/runner/trigger/trigger_runner.py
  py-sdk/sdk/poetry.lock
  py-sdk/sdk/sdk/auth/authentication.py
  py-sdk/sdk/sdk/auth/exceptions.py
  py-sdk/sdk/sdk/kai_sdk.py
  py-sdk/sdk/sdk/model_registry/model_registry.py
  py-sdk/sdk/sdk/persistent_storage/persistent_storage.py
Labels: size/xl
