Repository konstellation-io/kai-sdk, pull requests merged in 2023-11, with the labels that each got.

#81 Add persistent storage methods to the Go SDK
  demo/exit-py/main.py
  demo/exit/main.go
  demo/task/main.go
  go-sdk/go.mod
  go-sdk/go.sum
  go-sdk/internal/common/kai_constants.go
  go-sdk/internal/errors/errors.go
  go-sdk/mocks/ephemeral_storage_mock.go
  go-sdk/mocks/jetstream_context_mock.go
  go-sdk/mocks/key_value_entry_mock.go
  go-sdk/mocks/key_value_mock.go
  go-sdk/mocks/messaging_mock.go
  go-sdk/mocks/messaging_utils_mock.go
  go-sdk/mocks/metadata_mock.go
  go-sdk/mocks/minio_client_mock.go
  go-sdk/mocks/nats_object_store_mock.go
  go-sdk/mocks/path_utils_mock.go
  go-sdk/mocks/persistent_storage_mock.go
  go-sdk/runner/common/common.go
  go-sdk/runner/exit/helpers.go
  go-sdk/runner/exit/subscriber.go
  go-sdk/runner/runner.go
  go-sdk/runner/runner_test.go
  go-sdk/runner/task/helpers.go
  go-sdk/runner/task/subscriber.go
  go-sdk/runner/trigger/helpers.go
  go-sdk/runner/trigger/subscriber.go
  go-sdk/sdk/centralized-configuration/centralized_configuration.go
  go-sdk/sdk/centralized-configuration/centralized_configuration_test.go
  go-sdk/sdk/ephemeral-storage/ephemeral_storage.go
  go-sdk/sdk/ephemeral-storage/ephemeral_storage_delete_test.go
  go-sdk/sdk/kai_sdk.go
  go-sdk/sdk/messaging/messaging.go
  go-sdk/sdk/messaging/messaging_internals.go
  go-sdk/sdk/messaging/messaging_send_any_test.go
  go-sdk/sdk/messaging/messaging_test.go
  go-sdk/sdk/messaging/messaging_utils.go
  go-sdk/sdk/metadata/metadata.go
  go-sdk/sdk/metadata/metadata_test.go
  go-sdk/sdk/path-utils/path_utils.go
  go-sdk/sdk/path-utils/path_utils_test.go
  go-sdk/sdk/persistent-storage/export_test.go
  go-sdk/sdk/persistent-storage/persistent_storage.go
  go-sdk/sdk/persistent-storage/persistent_storage_delete_test.go
  go-sdk/sdk/persistent-storage/persistent_storage_get_test.go
  go-sdk/sdk/persistent-storage/persistent_storage_list_test.go
  go-sdk/sdk/persistent-storage/persistent_storage_list_versions_test.go
  go-sdk/sdk/persistent-storage/persistent_storage_save_test.go
  go-sdk/sdk/persistent-storage/persistent_storage_test.go
  go-sdk/sonar-project.properties
  py-sdk/sonar-project.properties
Labels: size/xl

#91 Authentication persistent storage GO
  demo/cronjob-trigger-py/app.yaml
  demo/cronjob-trigger/app.yaml
  demo/exit-py/app.yaml
  demo/exit/app.yaml
  demo/exit/main.go
  demo/nats-trigger-py/app.yaml
  demo/nats-trigger/app.yaml
  demo/rest-trigger/app.yaml
  demo/task-py/app.yaml
  demo/task/app.yaml
  demo/task/main.go
  go-sdk/go.mod
  go-sdk/go.sum
  go-sdk/internal/auth/authentication.go
  go-sdk/internal/common/kai_constants.go
  go-sdk/mocks/persistent_storage_mock.go
  go-sdk/runner/runner.go
  go-sdk/sdk/kai_sdk.go
  go-sdk/sdk/persistent-storage/export_test.go
  go-sdk/sdk/persistent-storage/persistent_storage.go
  go-sdk/sdk/persistent-storage/persistent_storage_get_test.go
  go-sdk/sdk/persistent-storage/persistent_storage_list_test.go
  go-sdk/sdk/persistent-storage/persistent_storage_list_versions_test.go
  go-sdk/sdk/persistent-storage/persistent_storage_save_test.go
  go-sdk/sdk/persistent-storage/persistent_storage_test.go
  py-sdk/runner/runner/runner.py
  py-sdk/sdk/sdk/persistent_storage/persistent_storage.py
  py-sdk/sdk/sdk/persistent_storage/persistent_storage_test.py
  testdata/config.yaml
Labels: size/l

#96 Create lifecycle policies only when they don't exist already
  go-sdk/sdk/persistent-storage/persistent_storage.go
Labels: size/s

#92 Authentication persistent storage PY
  demo/cronjob-trigger-py/main.py
  go-sdk/protos/kai_nats_msg.pb.go
  go-sdk/sdk/persistent-storage/export_test.go
  go-sdk/sdk/persistent-storage/persistent_storage.go
  go-sdk/sdk/persistent-storage/persistent_storage_get_test.go
  go-sdk/sdk/persistent-storage/persistent_storage_list_test.go
  go-sdk/sdk/persistent-storage/persistent_storage_list_versions_test.go
  py-sdk/poetry.lock
  py-sdk/pyproject.toml
  py-sdk/runner/poetry.lock
  py-sdk/runner/runner/runner.py
  py-sdk/sdk/poetry.lock
  py-sdk/sdk/pyproject.toml
  py-sdk/sdk/sdk/auth/__init__.py
  py-sdk/sdk/sdk/auth/authentication.py
  py-sdk/sdk/sdk/kai_nats_msg_pb2.py
  py-sdk/sdk/sdk/persistent_storage/persistent_storage.py
  py-sdk/sdk/sdk/persistent_storage/persistent_storage_test.py
Labels: size/xl

#97 feat: update log to go standard for fluentbint
  demo/cronjob-trigger-py/config.yaml
  demo/exit-py/config.yaml
  demo/nats-trigger-py/config.yaml
  demo/task-py/config.yaml
  go-sdk/runner/common/common.go
  go-sdk/runner/exit/helpers.go
  go-sdk/runner/exit/subscriber.go
  go-sdk/runner/runner.go
  go-sdk/runner/task/helpers.go
  go-sdk/runner/task/subscriber.go
  go-sdk/runner/trigger/helpers.go
  go-sdk/runner/trigger/subscriber.go
  go-sdk/sdk/centralized-configuration/centralized_configuration.go
  go-sdk/sdk/ephemeral-storage/ephemeral_storage.go
  go-sdk/sdk/kai_sdk.go
  go-sdk/sdk/messaging/messaging_internals.go
  go-sdk/sdk/persistent-storage/persistent_storage.go
  py-sdk/runner/runner/common/common.py
  py-sdk/runner/runner/exit/exit_runner.py
  py-sdk/runner/runner/exit/helpers.py
  py-sdk/runner/runner/exit/subscriber.py
  py-sdk/runner/runner/runner.py
  py-sdk/runner/runner/runner_test.py
  py-sdk/runner/runner/task/helpers.py
  py-sdk/runner/runner/task/subscriber.py
  py-sdk/runner/runner/task/task_runner.py
  py-sdk/runner/runner/trigger/helpers.py
  py-sdk/runner/runner/trigger/subscriber.py
  py-sdk/runner/runner/trigger/trigger_runner.py
  py-sdk/sdk/sdk/auth/authentication.py
  py-sdk/sdk/sdk/centralized_config/centralized_config.py
  py-sdk/sdk/sdk/ephemeral_storage/ephemeral_storage.py
  py-sdk/sdk/sdk/kai_sdk.py
  py-sdk/sdk/sdk/messaging/messaging.py
  py-sdk/sdk/sdk/messaging/messaging_utils.py
  py-sdk/sdk/sdk/path_utils/path_utils.py
  py-sdk/sdk/sdk/path_utils/paths_utils_test.py
  py-sdk/sdk/sdk/persistent_storage/persistent_storage.py
Labels: size/l

#101 feat: update serializer to match go serializer
  py-sdk/runner/runner/runner.py
Labels: size/s

#102 Feature/make python log global
  demo/cronjob-trigger-py/config.yaml
  demo/cronjob-trigger-py/main.py
  demo/cronjob-trigger-py/poetry.lock
  demo/cronjob-trigger/config.yaml
  demo/exit-py/config.yaml
  demo/exit-py/poetry.lock
  demo/exit/config.yaml
  demo/nats-trigger-py/config.yaml
  demo/nats-trigger/config.yaml
  demo/rest-trigger/config.yaml
  demo/task-py/config.yaml
  demo/task-py/poetry.lock
  demo/task/config.yaml
  go-sdk/config.yaml
  py-sdk/runner/runner/exit/helpers.py
  py-sdk/runner/runner/exit/subscriber.py
  py-sdk/runner/runner/task/helpers.py
  py-sdk/runner/runner/task/subscriber.py
  py-sdk/runner/runner/trigger/subscriber.py
  py-sdk/sdk/sdk/kai_sdk.py
  testdata/config.yaml
Labels: size/xl

#103 feat: update dependencies
  py-sdk/poetry.lock
  py-sdk/runner/poetry.lock
Labels: size/m

#105 Fix/avoid str dict
  py-sdk/runner/runner/exit/exit_runner.py
  py-sdk/runner/runner/runner.py
  py-sdk/runner/runner/task/task_runner.py
  py-sdk/runner/runner/trigger/helpers.py
  py-sdk/runner/runner/trigger/trigger_runner.py
  py-sdk/sdk/sdk/kai_sdk.py
Labels: size/s

#106 feat: update runner deps
  py-sdk/runner/poetry.lock
Labels: size/xs

#104 Refactor logger implementation in Go
  demo/cronjob-trigger/main.go
  demo/nats-trigger/main.go
  demo/rest-trigger/main.go
  go-sdk/internal/auth/authentication.go
  go-sdk/internal/common/kai_constants.go
  go-sdk/runner/common/common.go
  go-sdk/runner/common/common_test.go
  go-sdk/runner/exit/helpers.go
  go-sdk/runner/runner.go
  go-sdk/runner/task/helpers.go
  go-sdk/runner/trigger/helpers.go
  go-sdk/sdk/centralized-configuration/centralized_configuration.go
  go-sdk/sdk/ephemeral-storage/ephemeral_storage.go
  go-sdk/sdk/kai_sdk.go
  go-sdk/sdk/messaging/messaging.go
  go-sdk/sdk/messaging/messaging_internals.go
  go-sdk/sdk/path-utils/path_utils.go
  go-sdk/sdk/path-utils/path_utils_test.go
  go-sdk/sdk/persistent-storage/persistent_storage.go
  py-sdk/runner/runner/runner.py
  py-sdk/runner/runner/runner_test.py
  py-sdk/sdk/sdk/kai_sdk.py
  py-sdk/sdk/sdk/kai_sdk_test.py
  py-sdk/sdk/sdk/path_utils/__init__.py
  py-sdk/sdk/sdk/path_utils/path_utils.py
  py-sdk/sdk/sdk/path_utils/paths_utils_test.py
Labels: size/l

#108 feat: delete deprecated mock
  go-sdk/mocks/path_utils_mock.go
Labels: size/m

#109 feature(go-sdk): update all processes' sdk version
  demo/cronjob-trigger/go.mod
  demo/cronjob-trigger/go.sum
  demo/exit/go.mod
  demo/exit/go.sum
  demo/nats-trigger/go.mod
  demo/nats-trigger/go.sum
  demo/rest-trigger/go.mod
  demo/rest-trigger/go.sum
  demo/task/go.mod
  demo/task/go.sum
Labels: size/m

#111 fix: nump nats version to avoid crash with dependencies
  py-sdk/sdk/poetry.lock
  py-sdk/sdk/pyproject.toml
Labels: size/s

#110 Fix/avoid request id leaking
  .github/workflows/test.yaml
  Makefile
  demo/cronjob-trigger-py/poetry.lock
  demo/cronjob-trigger-py/pyproject.toml
  demo/exit-py/poetry.lock
  demo/exit-py/pyproject.toml
  demo/nats-trigger-py/poetry.lock
  demo/nats-trigger-py/pyproject.toml
  demo/task-py/poetry.lock
  demo/task-py/pyproject.toml
  py-sdk/poetry.lock
  py-sdk/pyproject.toml
  py-sdk/runner/poetry.lock
  py-sdk/runner/pyproject.toml
  py-sdk/runner/runner/exit/subscriber.py
  py-sdk/runner/runner/runner.py
  py-sdk/runner/runner/task/subscriber.py
  py-sdk/runner/runner/trigger/subscriber.py
  py-sdk/sdk/pyproject.toml
  py-sdk/sdk/sdk/kai_sdk.py
Labels: size/m

#116 Model registry methods Python
  go-sdk/go.mod
  go-sdk/go.sum
  go-sdk/sdk/model-registry/model_registry.go
  go-sdk/sdk/model-registry/model_registry_get_model_test.go
  go-sdk/sonar-project.properties
  py-sdk/poetry.lock
  py-sdk/pyproject.toml
  py-sdk/runner/poetry.lock
  py-sdk/runner/runner/common/common_test.py
  py-sdk/runner/runner/exit/exit_runner_test.py
  py-sdk/runner/runner/exit/helpers_test.py
  py-sdk/runner/runner/exit/subscriber_test.py
  py-sdk/runner/runner/runner_test.py
  py-sdk/runner/runner/task/helpers_test.py
  py-sdk/runner/runner/task/subscriber_test.py
  py-sdk/runner/runner/task/task_runner_test.py
  py-sdk/runner/runner/trigger/helpers_test.py
  py-sdk/runner/runner/trigger/subscriber_test.py
  py-sdk/runner/runner/trigger/trigger_runner_test.py
  py-sdk/sdk/poetry.lock
  py-sdk/sdk/pyproject.toml
  py-sdk/sdk/sdk/kai_sdk.py
  py-sdk/sdk/sdk/kai_sdk_test.py
  py-sdk/sdk/sdk/model_registry/__init__.py
  py-sdk/sdk/sdk/model_registry/exceptions.py
  py-sdk/sdk/sdk/model_registry/model_registry.py
  py-sdk/sdk/sdk/model_registry/model_registry_test.py
  py-sdk/sdk/sdk/persistent_storage/persistent_storage.py
  py-sdk/sdk/sdk/persistent_storage/persistent_storage_test.py
  py-sdk/sonar-project.properties
Labels: size/xl

#117 fix: wrong config file
  demo/redis-py/main.py
  testdata/config.yaml
Labels: size/s

#120 feat: update dependencies
  demo/cronjob-trigger-py/app.yaml
  demo/cronjob-trigger-py/pyproject.toml
  demo/cronjob-trigger/app.yaml
  demo/cronjob-trigger/go.mod
  demo/cronjob-trigger/go.sum
  demo/exit-py/app.yaml
  demo/exit-py/pyproject.toml
  demo/exit/app.yaml
  demo/exit/go.mod
  demo/exit/go.sum
  demo/metrics-py/app.yaml
  demo/metrics-py/pyproject.toml
  demo/metrics/app.yaml
  demo/metrics/go.mod
  demo/metrics/go.sum
  demo/nats-trigger-py/app.yaml
  demo/nats-trigger-py/pyproject.toml
  demo/nats-trigger/app.yaml
  demo/nats-trigger/go.mod
  demo/nats-trigger/go.sum
  demo/redis-py/pyproject.toml
  demo/rest-trigger/app.yaml
  demo/rest-trigger/go.mod
  demo/rest-trigger/go.sum
  demo/task-py/app.yaml
  demo/task-py/pyproject.toml
  demo/task/app.yaml
  demo/task/go.mod
  demo/task/go.sum
  py-sdk/poetry.lock
  py-sdk/pyproject.toml
  py-sdk/runner/poetry.lock
  py-sdk/runner/pyproject.toml
Labels: size/l

#121 release python runner
  demo/cronjob-trigger-py/app.yaml
  demo/cronjob-trigger-py/pyproject.toml
  demo/cronjob-trigger/app.yaml
  demo/cronjob-trigger/go.mod
  demo/cronjob-trigger/go.sum
  demo/exit-py/app.yaml
  demo/exit-py/pyproject.toml
  demo/exit/app.yaml
  demo/exit/go.mod
  demo/exit/go.sum
  demo/metrics-py/app.yaml
  demo/metrics-py/pyproject.toml
  demo/metrics/app.yaml
  demo/metrics/go.mod
  demo/metrics/go.sum
  demo/nats-trigger-py/app.yaml
  demo/nats-trigger-py/pyproject.toml
  demo/nats-trigger/app.yaml
  demo/nats-trigger/go.mod
  demo/nats-trigger/go.sum
  demo/redis-py/pyproject.toml
  demo/rest-trigger/app.yaml
  demo/rest-trigger/go.mod
  demo/rest-trigger/go.sum
  demo/task-py/app.yaml
  demo/task-py/pyproject.toml
  demo/task/app.yaml
  demo/task/go.mod
  demo/task/go.sum
  py-sdk/poetry.lock
  py-sdk/pyproject.toml
  py-sdk/runner/poetry.lock
  py-sdk/runner/pyproject.toml
Labels: size/l

#123 feat: update dependencies
  demo/cronjob-trigger-py/poetry.lock
  demo/exit-py/poetry.lock
  demo/metrics-py/poetry.lock
  demo/nats-trigger-py/poetry.lock
  demo/redis-py/poetry.lock
  demo/task-py/poetry.lock
Labels: size/l
