Repository konstellation-io/kai-sdk, pull requests merged in 2023-09, with the labels that each got.

#24 Fix/ mypy solve errors & improve unit test coverage
  py-sdk/runner/runner/exit/exit_runner.py
  py-sdk/runner/runner/exit/helpers.py
  py-sdk/runner/runner/exit/helpers_test.py
  py-sdk/runner/runner/exit/subscriber.py
  py-sdk/runner/runner/exit/subscriber_test.py
  py-sdk/runner/runner/runner_test.py
  py-sdk/runner/runner/task/helpers.py
  py-sdk/runner/runner/task/helpers_test.py
  py-sdk/runner/runner/task/subscriber.py
  py-sdk/runner/runner/task/subscriber_test.py
  py-sdk/runner/runner/task/task_runner.py
  py-sdk/runner/runner/trigger/helpers.py
  py-sdk/runner/runner/trigger/helpers_test.py
  py-sdk/runner/runner/trigger/subscriber.py
  py-sdk/runner/runner/trigger/subscriber_test.py
  py-sdk/runner/runner/trigger/trigger_runner.py
  py-sdk/runner/runner/trigger/trigger_runner_test.py
  py-sdk/sdk/sdk/kai_sdk_test.py
  py-sdk/sdk/sdk/messaging/messaging.py
  py-sdk/sdk/sdk/messaging/messaging_test.py
  py-sdk/sdk/sdk/messaging/messaging_utils_test.py
Labels: size/m

#25 Remove krt file downloader and references
  .gitignore
  README.md
  krt-files-downloader/.golangci.yml
  krt-files-downloader/CHANGELOG.md
  krt-files-downloader/Dockerfile
  krt-files-downloader/README.md
  krt-files-downloader/cmd/krt-files-downloader/main.go
  krt-files-downloader/go.mod
  krt-files-downloader/go.sum
  krt-files-downloader/internal/adapter/config/config.go
  krt-files-downloader/internal/adapter/repository/mongodb/connection.go
  krt-files-downloader/internal/adapter/repository/mongodb/gridfs.go
  krt-files-downloader/internal/adapter/repository/mongodb/krt.go
  krt-files-downloader/internal/adapter/repository/mongodb/manager.go
  krt-files-downloader/internal/adapter/util/compress.go
  krt-files-downloader/internal/domain/repository/krt.go
  krt-files-downloader/internal/domain/usecase/_test/greeter-v1.krt
  krt-files-downloader/internal/domain/usecase/krt.go
  krt-files-downloader/internal/domain/usecase/krt_test.go
  krt-files-downloader/internal/mocks/repo_krt.go
  krt-files-downloader/package.json
  krt-files-downloader/sonar-project.properties
Labels: size/l

#26 Fix graceful shutdown for all runners
  demo/cronjob-trigger/go.mod
  demo/cronjob-trigger/go.sum
  demo/cronjob-trigger/main.go
  demo/task/go.mod
  demo/task/go.sum
  go-sdk/runner/exit/subscriber.go
  go-sdk/runner/task/subscriber.go
  go-sdk/runner/trigger/helpers.go
  go-sdk/runner/trigger/subscriber.go
  go-sdk/runner/trigger/trigger_runner.go
Labels: size/s

#27 Fix go linting
  .github/workflows/test.yaml
  go-sdk/.golangci.yml
  go-sdk/internal/errors/errors.go
  go-sdk/runner/common/common.go
  go-sdk/runner/errors.go
  go-sdk/runner/exit/exit_runner.go
  go-sdk/runner/exit/helpers.go
  go-sdk/runner/exit/subscriber.go
  go-sdk/runner/runner.go
  go-sdk/runner/task/helpers.go
  go-sdk/runner/task/subscriber.go
  go-sdk/runner/task/task_runner.go
  go-sdk/runner/trigger/helpers.go
  go-sdk/runner/trigger/subscriber.go
  go-sdk/runner/trigger/trigger_runner.go
  go-sdk/sdk/centralized-configuration/centralized_configuration_test.go
  go-sdk/sdk/centralized-configuration/export_test.go
  go-sdk/sdk/kai_sdk.go
  go-sdk/sdk/messaging/messaging.go
  go-sdk/sdk/messaging/messaging_internals.go
  go-sdk/sdk/messaging/messaging_test.go
  go-sdk/sdk/object-store/object_store.go
Labels: size/m

#28 fix: wrong config option
  Makefile
Labels: size/xs

#29 fix(demo): fix demo environment
  demo/cronjob-trigger/go.mod
  demo/cronjob-trigger/go.sum
  demo/krt.yaml
  demo/rest-trigger/go.mod
  demo/rest-trigger/go.sum
  demo/task/go.mod
  demo/task/go.sum
Labels: size/l

#33 feat(training): add validation process
  demo/training-workflow/src/exit/proto/training.pb.go
  demo/training-workflow/src/splitter/proto/training_pb2.py
  demo/training-workflow/src/splitter/proto/training_pb2.pyi
  demo/training-workflow/src/training-go/proto/training.pb.go
  demo/training-workflow/src/training-py/proto/training_pb2.py
  demo/training-workflow/src/training-py/proto/training_pb2.pyi
  demo/training-workflow/src/validation/Dockerfile
  demo/training-workflow/src/validation/go.mod
  demo/training-workflow/src/validation/go.sum
  demo/training-workflow/src/validation/main.go
  demo/training-workflow/src/validation/proto/training.pb.go
  demo/training-workflow/training.proto
Labels: size/l

#34 feat(training): exit process
  demo/training-workflow/src/exit/go.mod
  demo/training-workflow/src/exit/go.sum
  demo/training-workflow/src/exit/main.go
Labels: size/l

#35 feat(training): training-go process
  demo/training-workflow/src/training-go/go.mod
  demo/training-workflow/src/training-go/go.sum
  demo/training-workflow/src/training-go/main.go
Labels: size/l

#36 feat(training): add dockerfiles
  demo/training-workflow/src/exit/Dockerfile
  demo/training-workflow/src/training-go/Dockerfile
Labels: size/s

#37 fix: sdk dependency is not local anymore
  py-sdk/poetry.lock
  py-sdk/pyproject.toml
  py-sdk/runner/poetry.lock
  py-sdk/runner/pyproject.toml
  py-sdk/sdk/poetry.lock
Labels: size/m

#39 fix: missing config logic
  py-sdk/runner/runner/runner.py
Labels: size/xs

#42 feat: update sdk
  py-sdk/poetry.lock
  py-sdk/runner/poetry.lock
  py-sdk/sdk/poetry.lock
Labels: size/s

#43 feat: updated
  py-sdk/poetry.lock
  py-sdk/runner/poetry.lock
Labels: size/xs

#44 feat: bump sdk version
  py-sdk/sdk/pyproject.toml
Labels: size/xs

#45 feat: bump sdk version
  py-sdk/poetry.lock
  py-sdk/pyproject.toml
  py-sdk/runner/poetry.lock
  py-sdk/runner/pyproject.toml
Labels: size/s

#46 fix: test
  py-sdk/poetry.lock
  py-sdk/runner/poetry.lock
  py-sdk/runner/pyproject.toml
  py-sdk/runner/runner/runner.py
Labels: size/xs
