Repository konstellation-io/kai-sdk, pull requests merged in 2024-02, with the labels that each got.

#206 feat: add overwrite option when saving
  py-sdk/sdk/sdk/ephemeral_storage/ephemeral_storage.py
  py-sdk/sdk/sdk/ephemeral_storage/ephemeral_storage_test.py
Labels: size/s

#207 feat: remove early reply/exit logic, add missing methods to interface…
  demo/cronjob-trigger-py/pyproject.toml
  demo/exit-py/pyproject.toml
  demo/metrics-py/pyproject.toml
  demo/nats-trigger-py/pyproject.toml
  demo/redis-py/pyproject.toml
  demo/task-py/pyproject.toml
  go-sdk/mocks/messaging_mock.go
  go-sdk/mocks/model_registry_mock.go
  go-sdk/mocks/predictions_mock.go
  go-sdk/protos/kai_nats_msg.pb.go
  go-sdk/sdk/kai_sdk.go
  go-sdk/sdk/messaging/export_test.go
  go-sdk/sdk/messaging/messaging.go
  go-sdk/sdk/messaging/messaging_internals.go
  go-sdk/sdk/messaging/messaging_message_helpers_test.go
  go-sdk/sdk/messaging/messaging_send_early_exit_test.go
  go-sdk/sdk/messaging/messaging_send_early_reply_test.go
  go-sdk/sdk/messaging/messaging_test.go
  proto/kai_nats_msg.proto
  py-sdk/README.md
  py-sdk/pyproject.toml
  py-sdk/sdk/pyproject.toml
  py-sdk/sdk/sdk/kai_nats_msg_pb2.py
  py-sdk/sdk/sdk/kai_nats_msg_pb2.pyi
  py-sdk/sdk/sdk/messaging/messaging.py
  py-sdk/sdk/sdk/messaging/messaging_test.py
Labels: size/xl

#205 fix: knt1 867 persistent storage command fixes
  py-sdk/poetry.lock
  py-sdk/sdk/sdk/model_registry/model_registry.py
  py-sdk/sdk/sdk/persistent_storage/persistent_storage.py
  py-sdk/sdk/sdk/persistent_storage/persistent_storage_test.py
Labels: size/s

#209 Feature/knt1 871 more metada info sdk
  demo/cronjob-trigger-py/app.yaml
  demo/cronjob-trigger/app.yaml
  demo/exit-py/app.yaml
  demo/exit/app.yaml
  demo/metrics-py/app.yaml
  demo/metrics/app.yaml
  demo/nats-trigger-py/app.yaml
  demo/nats-trigger/app.yaml
  demo/redis-py/app.yaml
  demo/rest-trigger/app.yaml
  demo/task-py/app.yaml
  demo/task/app.yaml
  go-sdk/internal/common/kai_constants.go
  go-sdk/mocks/metadata_mock.go
  go-sdk/runner/runner.go
  go-sdk/sdk/kai_sdk.go
  go-sdk/sdk/metadata/metadata.go
  py-sdk/runner/runner.py
  py-sdk/sdk/sdk/kai_sdk.py
  py-sdk/sdk/sdk/metadata/metadata.py
  py-sdk/sdk/sdk/metadata/metadata_test.py
  testdata/config.yaml
Labels: size/m

#210 Feature/knt1 870 predictions store new method
  go-sdk/sdk/kai_sdk.go
  go-sdk/sdk/prediction/delete.go
  go-sdk/sdk/prediction/delete_test.go
  go-sdk/sdk/prediction/find.go
  go-sdk/sdk/prediction/save_test.go
  py-sdk/poetry.lock
  py-sdk/sdk/sdk/predictions/exceptions.py
  py-sdk/sdk/sdk/predictions/store.py
  py-sdk/sdk/sdk/predictions/store_test.py
Labels: size/m

#211 feat: new metric number of messages processed
  go-sdk/runner/exit/exit_runner.go
  go-sdk/runner/exit/subscriber.go
  go-sdk/runner/task/subscriber.go
  go-sdk/runner/task/task_runner.go
  go-sdk/runner/trigger/subscriber.go
  go-sdk/runner/trigger/trigger_runner.go
  py-sdk/runner/exit/exit_runner.py
  py-sdk/runner/exit/subscriber.py
  py-sdk/runner/exit/subscriber_test.py
  py-sdk/runner/task/subscriber.py
  py-sdk/runner/task/subscriber_test.py
  py-sdk/runner/task/task_runner.py
  py-sdk/runner/trigger/subscriber.py
  py-sdk/runner/trigger/subscriber_test.py
  py-sdk/runner/trigger/trigger_runner.py
Labels: size/m

#212 fix: nats py bug workaround
  py-sdk/sdk/sdk/ephemeral_storage/ephemeral_storage.py
Labels: size/xs

#213 Fix/knt1 896 aio sdk demo feedback fixes
  go-sdk/.goimportsignore
  go-sdk/.golangci.yml
  go-sdk/internal/errors/errors.go
  go-sdk/internal/storage/minio_storage.go
  go-sdk/mocks/centralized_config_mock.go
  go-sdk/mocks/messaging_mock.go
  go-sdk/mocks/model_registry_mock.go
  go-sdk/mocks/predictions_mock.go
  go-sdk/runner/trigger/helpers.go
  go-sdk/sdk/centralized-configuration/centralized_configuration.go
  go-sdk/sdk/centralized-configuration/centralized_configuration_delete_test.go
  go-sdk/sdk/centralized-configuration/centralized_configuration_get_test.go
  go-sdk/sdk/centralized-configuration/centralized_configuration_set_test.go
  go-sdk/sdk/centralized-configuration/centralized_configuration_test.go
  go-sdk/sdk/kai_sdk.go
  go-sdk/sdk/messaging/messaging.go
  go-sdk/sdk/messaging/messaging_internals.go
  go-sdk/sdk/messaging/messaging_test.go
  go-sdk/sdk/model-registry/model_registry.go
  go-sdk/sdk/model-registry/model_registry_get_model_test.go
  go-sdk/sdk/model-registry/model_registry_list_models_test.go
  go-sdk/sdk/model-registry/model_registry_register_model_test.go
  go-sdk/sdk/model-registry/model_registry_test.go
  py-sdk/sdk/sdk/messaging/messaging.py
  py-sdk/sdk/sdk/messaging/messaging_test.py
  py-sdk/sdk/sdk/model_registry/exceptions.py
  py-sdk/sdk/sdk/model_registry/model_registry.py
  py-sdk/sdk/sdk/model_registry/model_registry_test.py
  py-sdk/sdk/sdk/predictions/store.py
  py-sdk/sdk/sdk/predictions/store_test.py
Labels: size/l

#215 ci: fix python package publishing condition
  .github/workflows/python-publish-package.yaml
Labels: size/xs

#217 fix: py sdk naming
  py-sdk/README.md
  py-sdk/pyproject.toml
  py-sdk/sdk/pyproject.toml
Labels: size/s

#218 Merge develop into main
  .ci/tools/bump_version.sh
  .github/workflows/python-publish-package.yaml
  py-sdk/README.md
  py-sdk/pyproject.toml
  py-sdk/sdk/pyproject.toml
Labels: size/s

#219 Fix/register model python
  py-sdk/sdk/sdk/model_registry/model_registry.py
  py-sdk/sdk/sdk/model_registry/model_registry_test.py
Labels: size/s

#220 ci: add multi-semantic-release config
  .github/workflows/test-release.yaml
  go-sdk/package.json
  package.json
  py-sdk/package.json
Labels: size/s

#222 Release/v2.0.1
  .github/workflows/test-release.yaml
  go-sdk/package.json
  package.json
  py-sdk/package.json
  py-sdk/sdk/sdk/model_registry/model_registry.py
  py-sdk/sdk/sdk/model_registry/model_registry_test.py
Labels: size/s

#224 ci: bump dependencies
  demo/cronjob-trigger-py/Dockerfile
  demo/cronjob-trigger-py/develop.Dockerfile
  demo/cronjob-trigger-py/poetry.lock
  demo/cronjob-trigger-py/pyproject.toml
  demo/cronjob-trigger/go.mod
  demo/cronjob-trigger/go.sum
  demo/cronjob-trigger/main.go
  demo/exit-py/Dockerfile
  demo/exit-py/develop.Dockerfile
  demo/exit-py/poetry.lock
  demo/exit-py/pyproject.toml
  demo/exit/go.mod
  demo/exit/go.sum
  demo/exit/main.go
  demo/metrics-py/Dockerfile
  demo/metrics-py/develop.Dockerfile
  demo/metrics-py/poetry.lock
  demo/metrics-py/pyproject.toml
  demo/metrics/go.mod
  demo/metrics/go.sum
  demo/metrics/main.go
  demo/nats-trigger-py/Dockerfile
  demo/nats-trigger-py/develop.Dockerfile
  demo/nats-trigger-py/main.py
  demo/nats-trigger-py/poetry.lock
  demo/nats-trigger-py/pyproject.toml
  demo/nats-trigger/go.mod
  demo/nats-trigger/go.sum
  demo/nats-trigger/main.go
  demo/redis-py/Dockerfile
  demo/redis-py/develop.Dockerfile
  demo/redis-py/poetry.lock
  demo/redis-py/pyproject.toml
  demo/rest-trigger/go.mod
  demo/rest-trigger/go.sum
  demo/rest-trigger/main.go
  demo/task-py/Dockerfile
  demo/task-py/develop.Dockerfile
  demo/task-py/poetry.lock
  demo/task-py/pyproject.toml
  demo/task/go.mod
  demo/task/go.sum
  demo/task/main.go
  go-sdk/protos/kai_nats_msg.pb.go
Labels: size/xl

#226 Fix/update readme
  README.md
  go-sdk/Dockerfile
  go-sdk/README.md
  py-sdk/README.md
  py-sdk/runner/exit/exit_runner.py
  py-sdk/runner/task/task_runner.py
  py-sdk/runner/trigger/trigger_runner.py
Labels: size/m

#225 merge branch develop into main
  README.md
  demo/cronjob-trigger-py/Dockerfile
  demo/cronjob-trigger-py/develop.Dockerfile
  demo/cronjob-trigger-py/poetry.lock
  demo/cronjob-trigger-py/pyproject.toml
  demo/cronjob-trigger/go.mod
  demo/cronjob-trigger/go.sum
  demo/cronjob-trigger/main.go
  demo/exit-py/Dockerfile
  demo/exit-py/develop.Dockerfile
  demo/exit-py/poetry.lock
  demo/exit-py/pyproject.toml
  demo/exit/go.mod
  demo/exit/go.sum
  demo/exit/main.go
  demo/metrics-py/Dockerfile
  demo/metrics-py/develop.Dockerfile
  demo/metrics-py/poetry.lock
  demo/metrics-py/pyproject.toml
  demo/metrics/go.mod
  demo/metrics/go.sum
  demo/metrics/main.go
  demo/nats-trigger-py/Dockerfile
  demo/nats-trigger-py/develop.Dockerfile
  demo/nats-trigger-py/main.py
  demo/nats-trigger-py/poetry.lock
  demo/nats-trigger-py/pyproject.toml
  demo/nats-trigger/go.mod
  demo/nats-trigger/go.sum
  demo/nats-trigger/main.go
  demo/redis-py/Dockerfile
  demo/redis-py/develop.Dockerfile
  demo/redis-py/poetry.lock
  demo/redis-py/pyproject.toml
  demo/rest-trigger/go.mod
  demo/rest-trigger/go.sum
  demo/rest-trigger/main.go
  demo/task-py/Dockerfile
  demo/task-py/develop.Dockerfile
  demo/task-py/poetry.lock
  demo/task-py/pyproject.toml
  demo/task/go.mod
  demo/task/go.sum
  demo/task/main.go
  go-sdk/Dockerfile
  go-sdk/README.md
  go-sdk/protos/kai_nats_msg.pb.go
  py-sdk/README.md
  py-sdk/runner/exit/exit_runner.py
  py-sdk/runner/task/task_runner.py
  py-sdk/runner/trigger/trigger_runner.py
Labels: size/xl

#228 test: remove explicit boundaries
  go-sdk/runner/exit/subscriber.go
  py-sdk/sdk/sdk/measurements/measurements.py
Labels: size/xs

#231 Fix/update metrics
  go-sdk/runner/exit/exit_runner.go
  go-sdk/runner/exit/subscriber.go
  go-sdk/runner/task/subscriber.go
  go-sdk/runner/task/task_runner.go
  go-sdk/runner/trigger/subscriber.go
  go-sdk/runner/trigger/trigger_runner.go
  py-sdk/runner/exit/exit_runner.py
  py-sdk/runner/exit/subscriber.py
  py-sdk/runner/exit/subscriber_test.py
  py-sdk/runner/task/subscriber.py
  py-sdk/runner/task/subscriber_test.py
  py-sdk/runner/task/task_runner.py
  py-sdk/runner/trigger/subscriber.py
  py-sdk/runner/trigger/subscriber_test.py
  py-sdk/runner/trigger/trigger_runner.py
Labels: size/m

#232 Release/v2.1.1
  go-sdk/runner/exit/exit_runner.go
  go-sdk/runner/exit/subscriber.go
  go-sdk/runner/task/subscriber.go
  go-sdk/runner/task/task_runner.go
  go-sdk/runner/trigger/subscriber.go
  go-sdk/runner/trigger/trigger_runner.go
  py-sdk/runner/exit/exit_runner.py
  py-sdk/runner/exit/subscriber.py
  py-sdk/runner/exit/subscriber_test.py
  py-sdk/runner/task/subscriber.py
  py-sdk/runner/task/subscriber_test.py
  py-sdk/runner/task/task_runner.py
  py-sdk/runner/trigger/subscriber.py
  py-sdk/runner/trigger/subscriber_test.py
  py-sdk/runner/trigger/trigger_runner.py
Labels: size/m

#235 fix: outdated scripts after deleting demo folder, bump opentelemetry …
  Makefile
  py-sdk/poetry.lock
  py-sdk/pyproject.toml
  py-sdk/sdk/poetry.lock
  py-sdk/sdk/pyproject.toml
  scripts/update_go_mod.sh
  scripts/update_poetries.sh
Labels: size/m

#236 fix: outdated scripts after deleting demo folder, bump opentelemetry …
  Makefile
  py-sdk/poetry.lock
  py-sdk/pyproject.toml
  py-sdk/sdk/poetry.lock
  py-sdk/sdk/pyproject.toml
  scripts/update_go_mod.sh
  scripts/update_poetries.sh
Labels: size/m
